- include_tasks: addon.yml

- include_tasks: sp.yml

- include_tasks: agent_pool.yml

- include_tasks: network.yml

- include_tasks: aad.yml

- set_fact:
      dns_prefix: "{{ dns_prefix | default(name, true) }}"

- name: check if ssh file exists
  stat: 
      path: '~/.ssh/id_rsa.pub'
  register: ssh_file
  when: ssh_key is not defined

- name: Loading SSH public key file in '~/.ssh/id_rsa.pub'
  set_fact:
      ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ssh_key is not defined and ssh_file.stat.exists

- fail:
      msg: Cannot read ssh_key from input or load in ~/.ssh/id_ras.pub
  when: ssh_key is not defined
  name: ssh_key is unset

# - name: Set the undefined variable to None
#   set_fact:
#       "{{ item }}": ""
#   when: "{{ item }} is not defined"
#   with_items: "{{ parameter_list }}"